export const PRICING_CONFIG = {
  NORMAL_PRICE: 250,
  EARLY_ADOPTER_PRICE: 150,
  EARLY_ADOPTER_DISCOUNT_PERCENTAGE: 0.2, // 20%
  EARLY_ADOPTER_DISCOUNT_USAGE_LIMIT: 3,
  EARLY_ADOPTER_LIMIT: 10,
};
